# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'show_revnotes.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RevNoteWin(object):
    def setupUi(self, RevNoteWin):
        RevNoteWin.setObjectName("RevNoteWin")
        RevNoteWin.resize(898, 646)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(RevNoteWin.sizePolicy().hasHeightForWidth())
        RevNoteWin.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(RevNoteWin)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.lineSearch = QtWidgets.QLineEdit(self.centralwidget)
        self.lineSearch.setGeometry(QtCore.QRect(340, 520, 152, 37))
        self.lineSearch.setObjectName("lineSearch")
        self.txtContent = QtWidgets.QTextEdit(self.centralwidget)
        self.txtContent.setGeometry(QtCore.QRect(40, 150, 631, 231))
        self.txtContent.setObjectName("txtContent")
        self.txtTitle = QtWidgets.QTextEdit(self.centralwidget)
        self.txtTitle.setGeometry(QtCore.QRect(50, 40, 631, 87))
        self.txtTitle.setObjectName("txtTitle")
        self.btnPrev = QtWidgets.QPushButton(self.centralwidget)
        self.btnPrev.setGeometry(QtCore.QRect(560, 510, 105, 39))
        self.btnPrev.setObjectName("btnPrev")
        self.btnNext = QtWidgets.QPushButton(self.centralwidget)
        self.btnNext.setGeometry(QtCore.QRect(700, 510, 105, 39))
        self.btnNext.setObjectName("btnNext")
        self.btnVform = QtWidgets.QPushButton(self.centralwidget)
        self.btnVform.setGeometry(QtCore.QRect(90, 525, 84, 39))
        self.btnVform.setObjectName("btnVform")
        self.btnRefresh = QtWidgets.QPushButton(self.centralwidget)
        self.btnRefresh.setGeometry(QtCore.QRect(6, 525, 83, 39))
        self.btnRefresh.setObjectName("btnRefresh")
        self.btnDelete = QtWidgets.QPushButton(self.centralwidget)
        self.btnDelete.setGeometry(QtCore.QRect(175, 525, 83, 39))
        self.btnDelete.setObjectName("btnDelete")
        self.spinID = QtWidgets.QSpinBox(self.centralwidget)
        self.spinID.setGeometry(QtCore.QRect(730, 80, 56, 37))
        self.spinID.setObjectName("spinID")
        self.spinCat = QtWidgets.QSpinBox(self.centralwidget)
        self.spinCat.setGeometry(QtCore.QRect(730, 170, 56, 37))
        self.spinCat.setObjectName("spinCat")
        self.btnCopy = QtWidgets.QPushButton(self.centralwidget)
        self.btnCopy.setGeometry(QtCore.QRect(40, 440, 105, 39))
        self.btnCopy.setObjectName("btnCopy")
        RevNoteWin.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(RevNoteWin)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 898, 34))
        self.menubar.setObjectName("menubar")
        self.menu_File = QtWidgets.QMenu(self.menubar)
        self.menu_File.setObjectName("menu_File")
        RevNoteWin.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(RevNoteWin)
        self.statusbar.setObjectName("statusbar")
        RevNoteWin.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(RevNoteWin)
        self.toolBar.setObjectName("toolBar")
        RevNoteWin.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionExit = QtWidgets.QAction(RevNoteWin)
        self.actionExit.setObjectName("actionExit")
        self.menu_File.addAction(self.actionExit)
        self.menubar.addAction(self.menu_File.menuAction())

        self.retranslateUi(RevNoteWin)
        QtCore.QMetaObject.connectSlotsByName(RevNoteWin)

    def retranslateUi(self, RevNoteWin):
        _translate = QtCore.QCoreApplication.translate
        RevNoteWin.setWindowTitle(_translate("RevNoteWin", "Review Notes"))
        self.btnPrev.setText(_translate("RevNoteWin", "&Prev"))
        self.btnNext.setText(_translate("RevNoteWin", "&Next"))
        self.btnVform.setText(_translate("RevNoteWin", "Add &New"))
        self.btnRefresh.setText(_translate("RevNoteWin", "Refresh"))
        self.btnDelete.setText(_translate("RevNoteWin", "Delete"))
        self.btnCopy.setText(_translate("RevNoteWin", "&Copy"))
        self.menu_File.setTitle(_translate("RevNoteWin", "&File"))
        self.toolBar.setWindowTitle(_translate("RevNoteWin", "toolBar"))
        self.actionExit.setText(_translate("RevNoteWin", "Exit"))
